permalink: /blog/:year/:month/:title
language: pt
paginate: 5
paginate_path: "/blog/page:num/"
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []
